/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WantedRouteImport } from './routes/wanted'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as LibraryNameRouteImport } from './routes/library.$name'
import { Route as ListenCodeRouteImport } from './routes/listen.$code'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as TitleIdRouteImport } from './routes/title.$id'
import { Route as TogetherCodeRouteImport } from './routes/together.$code'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WantedRoute = WantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryNameRoute = LibraryNameRouteImport.update({
  id: '/library/$name',
  path: '/library/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenCodeRoute = ListenCodeRouteImport.update({
  id: '/listen/$code',
  path: '/listen/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherCodeRoute = TogetherCodeRouteImport.update({
  id: '/together/$code',
  path: '/together/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clips': typeof ClipsRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/invite': typeof InviteRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/wanted': typeof WantedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/library/$name': typeof LibraryNameRoute
  '/listen/$code': typeof ListenCodeRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/title/$id': typeof TitleIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clips': typeof ClipsRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/invite': typeof InviteRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/wanted': typeof WantedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/library/$name': typeof LibraryNameRoute
  '/listen/$code': typeof ListenCodeRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/title/$id': typeof TitleIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clips': typeof ClipsRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/invite': typeof InviteRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/wanted': typeof WantedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/library/$name': typeof LibraryNameRoute
  '/listen/$code': typeof ListenCodeRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/title/$id': typeof TitleIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/clips'
    | '/discover'
    | '/downloads'
    | '/invite'
    | '/requests'
    | '/settings'
    | '/wanted'
    | '/album/$id'
    | '/artist/$id'
    | '/library/$name'
    | '/listen/$code'
    | '/playlist/$id'
    | '/title/$id'
    | '/together/$code'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/clips'
    | '/discover'
    | '/downloads'
    | '/invite'
    | '/requests'
    | '/settings'
    | '/wanted'
    | '/album/$id'
    | '/artist/$id'
    | '/library/$name'
    | '/listen/$code'
    | '/playlist/$id'
    | '/title/$id'
    | '/together/$code'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/clips'
    | '/discover'
    | '/downloads'
    | '/invite'
    | '/requests'
    | '/settings'
    | '/wanted'
    | '/album/$id'
    | '/artist/$id'
    | '/library/$name'
    | '/listen/$code'
    | '/playlist/$id'
    | '/title/$id'
    | '/together/$code'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ClipsRoute: typeof ClipsRoute
  DiscoverRoute: typeof DiscoverRoute
  DownloadsRoute: typeof DownloadsRoute
  InviteRoute: typeof InviteRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  WantedRoute: typeof WantedRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  LibraryNameRoute: typeof LibraryNameRoute
  ListenCodeRoute: typeof ListenCodeRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  TitleIdRoute: typeof TitleIdRoute
  TogetherCodeRoute: typeof TogetherCodeRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanted': {
      id: '/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof WantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$name': {
      id: '/library/$name'
      path: '/library/$name'
      fullPath: '/library/$name'
      preLoaderRoute: typeof LibraryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$code': {
      id: '/listen/$code'
      path: '/listen/$code'
      fullPath: '/listen/$code'
      preLoaderRoute: typeof ListenCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together/$code': {
      id: '/together/$code'
      path: '/together/$code'
      fullPath: '/together/$code'
      preLoaderRoute: typeof TogetherCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ClipsRoute: ClipsRoute,
  DiscoverRoute: DiscoverRoute,
  DownloadsRoute: DownloadsRoute,
  InviteRoute: InviteRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  WantedRoute: WantedRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  LibraryNameRoute: LibraryNameRoute,
  ListenCodeRoute: ListenCodeRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  TitleIdRoute: TitleIdRoute,
  TogetherCodeRoute: TogetherCodeRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>
  }
}
